#!/usr/bin/env node
/*
 * build-web.js
 *
 * Bundles the renderer + assets + web shell into ./docs/ so GitHub Pages
 * can serve them. Cross-platform — works on macOS, Linux and Windows
 * without bash.
 *
 * Usage:
 *   node build-web.js
 *   npm run build:web
 *
 * After running, commit the contents of ./docs/ to your repo and configure
 * GitHub Pages to deploy from "main /docs". See README.md for details.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT  = path.join(ROOT, 'docs');

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else                     fs.copyFileSync(s, d);
  }
}

function writeFile(rel, content) {
  fs.writeFileSync(path.join(OUT, rel), content);
}

console.log('Building web bundle into', OUT);

// Wipe and recreate the output folder. If the wipe fails (e.g. in a
// sandboxed filesystem) just continue — copyFileSync below will overwrite
// any existing files, which is what matters.
try {
  if (fs.existsSync(OUT)) fs.rmSync(OUT, { recursive: true, force: true });
} catch (err) {
  console.warn('Could not wipe docs/ cleanly:', err.message, '— continuing with overwrite');
}
fs.mkdirSync(OUT, { recursive: true });

// 1) Renderer JS + CSS (everything in src/renderer/). The Electron-only
// index.html gets copied across here too, but step 4 below overwrites it
// with the web shell so we don't ship Electron-specific markup.
copyDir(path.join(ROOT, 'src', 'renderer'), OUT);

// 2) Assets (banks, scenarios)
copyDir(path.join(ROOT, 'assets'), path.join(OUT, 'assets'));

// 3) Icons — favicon + PWA sizes + maskable variant
const iconPng = path.join(ROOT, 'build', 'icon.png');
if (fs.existsSync(iconPng)) {
  fs.copyFileSync(iconPng, path.join(OUT, 'favicon.png'));
}
for (const name of ['icon-192.png', 'icon-512.png', 'icon-maskable-512.png']) {
  const src = path.join(ROOT, 'build', name);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(OUT, name));
}

// 4) Web shell HTML + bridge polyfill + PWA manifest + service worker
fs.copyFileSync(path.join(ROOT, 'web', 'index.html'),    path.join(OUT, 'index.html'));
fs.copyFileSync(path.join(ROOT, 'web', 'web-bridge.js'), path.join(OUT, 'web-bridge.js'));
fs.copyFileSync(path.join(ROOT, 'web', 'manifest.json'), path.join(OUT, 'manifest.json'));

// Stamp the service worker with a build version so that whenever we deploy,
// every user's browser sees a fresh service worker, drops the old cache,
// and re-precaches the new assets.
const swSource = fs.readFileSync(path.join(ROOT, 'web', 'sw.js'), 'utf8');
const buildVersion = new Date().toISOString().replace(/[:.]/g, '-');
fs.writeFileSync(path.join(OUT, 'sw.js'),
  swSource.replace('__BUILD_VERSION__', buildVersion));

// 5) Skip Jekyll processing on GitHub Pages
writeFile('.nojekyll', '');

// 6) Pin the build origin so anyone landing in /docs/ knows not to edit by hand
const stamp = new Date().toISOString();
writeFile('README.md',
`# DFSQ Practice — web build output

This folder is generated by \`node build-web.js\` (or \`npm run build:web\`)
from the source in \`src/renderer/\`, \`assets/\`, and \`web/\` of the repo.

Built: ${stamp}

**Do not edit files here directly** — edit the sources and re-run the build.
The site is deployed by GitHub Pages from the \`/docs\` folder on the
\`main\` branch.
`);

// 7) Report what we did
const files = [];
function walk(dir, base = '') {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = path.join(base, e.name);
    if (e.isDirectory()) walk(path.join(dir, e.name), rel);
    else files.push(rel);
  }
}
walk(OUT);
console.log('Wrote', files.length, 'files. Sample:');
for (const f of files.slice(0, 10)) console.log('  -', f);
console.log('');
console.log('Next steps:');
console.log('  git add docs && git commit -m "Update web build" && git push');
console.log('  Then enable GitHub Pages: Settings → Pages → Source: main /docs');
